name = "memos-worker"
compatibility_date = "2026-05-15"
main = "src/index.js"

[[d1_databases]]
binding = "DB"
database_id = "93d79940-083d-4089-b038-7b41a9bea60e"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "74002875f0ca4ce7aee26d94d1518f38"

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2"

